logging:
  level:
    root: INFO
    org.springframework.r2dbc.core: debug


spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3305/fastsns
    username: root
    password: qwer1234
  data:
    redis:
      host: 127.0.0.1
      port: 6369


